//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVARest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVARest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externe toegang token moet ingevuld zijn.
        /// </summary>
        public static string AddExternalLoginExternalAccessTokenRequired {
            get {
                return ResourceManager.GetString("AddExternalLoginExternalAccessTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to challenge type verplicht.
        /// </summary>
        public static string ChallengeTypeRequired {
            get {
                return ResourceManager.GetString("ChallengeTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het nieuw wachtwoord en confirmatie passwoord zijn niet gelijk..
        /// </summary>
        public static string ChangePasswordConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord verplicht.
        /// </summary>
        public static string ChangePasswordNewPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePasswordNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het {0} moet tenminste {2} karakters lang zijn..
        /// </summary>
        public static string ChangePasswordNewPasswordStringLength {
            get {
                return ResourceManager.GetString("ChangePasswordNewPasswordStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oud wachtwoord is moet ingevuld zijn.
        /// </summary>
        public static string ChangePasswordOldPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePasswordOldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nieuw wachtwoord.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmatie wachtwoord.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern toegang token.
        /// </summary>
        public static string ExternalAccessToken {
            get {
                return ResourceManager.GetString("ExternalAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lijst van string waarden verplicht.
        /// </summary>
        public static string ListOfStringValuesRequired {
            get {
                return ResourceManager.GetString("ListOfStringValuesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login provider.
        /// </summary>
        public static string LoginProvider {
            get {
                return ResourceManager.GetString("LoginProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidig wachtwoord.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wachtwoord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provider sleutel.
        /// </summary>
        public static string ProviderKey {
            get {
                return ResourceManager.GetString("ProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wachtwoord en confirmatie wachtwoord komen niet overeen..
        /// </summary>
        public static string RegisterConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("RegisterConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is verplicht.
        /// </summary>
        public static string RegisterEmailRequired {
            get {
                return ResourceManager.GetString("RegisterEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern email verplicht.
        /// </summary>
        public static string RegisterExternalEmailRequired {
            get {
                return ResourceManager.GetString("RegisterExternalEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord verplicht.
        /// </summary>
        public static string RegisterPasswordRequired {
            get {
                return ResourceManager.GetString("RegisterPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het {0} moet minstens {2} karakters lang zijn..
        /// </summary>
        public static string RegisterPasswordStringLength {
            get {
                return ResourceManager.GetString("RegisterPasswordStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login provider verplicht.
        /// </summary>
        public static string RemoveLoginLoginProviderRequired {
            get {
                return ResourceManager.GetString("RemoveLoginLoginProviderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login provider sleutel verplicht.
        /// </summary>
        public static string RemoveLoginProviderKeyRequired {
            get {
                return ResourceManager.GetString("RemoveLoginProviderKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het nieuw wachtwoord en confirmatie wachtwoord komen niet overeen..
        /// </summary>
        public static string SetPasswordConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("SetPasswordConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord verplicht.
        /// </summary>
        public static string SetPasswordNewPasswordRequired {
            get {
                return ResourceManager.GetString("SetPasswordNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het {0} moet tenminste {2} karakters lang zijn..
        /// </summary>
        public static string SetPasswordNewPasswordStringLength {
            get {
                return ResourceManager.GetString("SetPasswordNewPasswordStringLength", resourceCulture);
            }
        }
    }
}
